# Generated by Django 3.2.4 on 2021-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(default='Aspirational', help_text='To Store Img', max_length=300, null=True),
        ),
    ]
