# Generated by Django 3.1.2 on 2021-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20210618_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='latRef',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='longRef',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
