# Generated by Django 3.1.2 on 2021-06-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='user_id',
        ),
    ]
