# Generated by Django 3.1.2 on 2021-06-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20210619_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
    ]
